=head1 NAME

App::TemplateViewer -

=head1 SYNOPSIS

  use App::TemplateViewer;

=head1 DESCRIPTION

App::TemplateViewer is

=head1 AUTHOR

ywatase E<lt>ywatase@gmail.comE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

